# Generated by Django 4.2.3 on 2023-07-20 06:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basemodel')),
                ('name', models.TextField(max_length=50)),
            ],
            bases=('api.basemodel',),
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basemodel')),
                ('title', models.TextField(max_length=300)),
                ('img', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='api.categorymodel')),
            ],
            bases=('api.basemodel',),
        ),
        migrations.CreateModel(
            name='VarientModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basemodel')),
                ('price', models.IntegerField()),
                ('varients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varients', to='api.productmodel')),
            ],
            bases=('api.basemodel',),
        ),
        migrations.CreateModel(
            name='SizeModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basemodel')),
                ('price', models.IntegerField()),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='api.productmodel')),
            ],
            bases=('api.basemodel',),
        ),
        migrations.CreateModel(
            name='FavouriteModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basemodel')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.productmodel')),
            ],
            bases=('api.basemodel',),
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basemodel')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.productmodel')),
            ],
            bases=('api.basemodel',),
        ),
    ]
