# Generated by Django 4.2.3 on 2023-07-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sizemodel_product_name_varientmodel_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(default='mens shirt wear'),
            preserve_default=False,
        ),
    ]
