# Generated by Django 4.2.3 on 2023-07-31 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_productmodel_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='title',
            new_name='name',
        ),
    ]
