# Generated by Django 4.2.3 on 2023-08-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_productmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='status',
            field=models.CharField(choices=[('0', 'Draft'), ('1', 'Publish')], default='0', max_length=1),
        ),
    ]
