# Generated by Django 4.2.3 on 2023-08-07 06:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_categorymodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
