# Generated by Django 4.2.3 on 2023-08-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_productmodel_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='img',
            new_name='image',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image_alt',
            field=models.CharField(default='This is default for now', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='smDescription',
            field=models.CharField(default='this is deafailt description for now for all of the field', max_length=30),
            preserve_default=False,
        ),
    ]
