# Generated by Django 4.2.3 on 2023-08-09 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_img_productmodel_image_productmodel_image_alt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='image',
            new_name='thumbnail',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='image_alt',
            new_name='thumbnail_alt',
        ),
    ]
