# Generated by Django 4.2.3 on 2023-08-09 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_image_productmodel_thumbnail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LadingSlideModal',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basemodel')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('url', models.CharField(blank=True, max_length=50)),
            ],
            bases=('api.basemodel',),
        ),
        migrations.CreateModel(
            name='ProductImageModal',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basemodel')),
                ('image', models.ImageField(upload_to='')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_images', to='api.productmodel')),
            ],
            bases=('api.basemodel',),
        ),
    ]
