# Generated by Django 4.2.3 on 2023-08-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_ladingslidemodal_productimagemodal'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladingslidemodal',
            name='image_alt',
            field=models.CharField(default='csajbcjks da', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimagemodal',
            name='image_alt',
            field=models.CharField(default='csanclsca', max_length=50),
            preserve_default=False,
        ),
    ]
