# Generated by Django 4.2.3 on 2023-08-10 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_cartitemsmodal_usercartmodal_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ColorVarientModel',
            new_name='ColorVariantModel',
        ),
        migrations.RenameField(
            model_name='colorvariantmodel',
            old_name='varients',
            new_name='variants',
        ),
    ]
