# Generated by Django 4.2.3 on 2023-08-10 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_colorvarientmodel_colorvariantmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colorvariantmodel',
            old_name='variants',
            new_name='variant',
        ),
        migrations.AlterField(
            model_name='colorvariantmodel',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_variant', to='api.productmodel'),
        ),
        migrations.AlterField(
            model_name='sizemodel',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_variant', to='api.productmodel'),
        ),
    ]
