# Generated by Django 4.2.3 on 2023-08-10 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_variants_colorvariantmodel_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorvariantmodel',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='api.productmodel'),
        ),
        migrations.AlterField(
            model_name='sizemodel',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_variants', to='api.productmodel'),
        ),
    ]
