# Generated by Django 4.2.3 on 2023-08-10 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_colorvariantmodel_product_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SizeModel',
            new_name='SizeVariantModel',
        ),
        migrations.DeleteModel(
            name='FavouriteModel',
        ),
    ]
