# Generated by Django 4.2.3 on 2023-08-10 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_cartitemsmodal_produt_cartitemsmodal_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colorvariantmodel',
            old_name='variant',
            new_name='color',
        ),
    ]
