# Generated by Django 4.2.3 on 2023-08-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_variant_colorvariantmodel_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LadingSlideModal',
            new_name='LandingSlideModal',
        ),
        migrations.AlterModelOptions(
            name='cartitemsmodal',
            options={'verbose_name_plural': 'CartItemsModal'},
        ),
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'CategoryModal', 'verbose_name_plural': 'CategoryModal'},
        ),
        migrations.AlterModelOptions(
            name='colorvariantmodel',
            options={'verbose_name': 'ColorVariantModel', 'verbose_name_plural': 'ColorVariantModel'},
        ),
        migrations.AlterModelOptions(
            name='landingslidemodal',
            options={'verbose_name': 'LandingSlideModal', 'verbose_name_plural': 'LandingSlideModal'},
        ),
        migrations.AlterModelOptions(
            name='productimagemodal',
            options={'verbose_name': 'ProductImageModal', 'verbose_name_plural': 'ProductImageModal'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'ProductModel', 'verbose_name_plural': 'ProductModel'},
        ),
        migrations.AlterModelOptions(
            name='saveditemsmodal',
            options={'verbose_name': 'SavedItemsModal', 'verbose_name_plural': 'SavedItemsModal'},
        ),
        migrations.AlterModelOptions(
            name='sizevariantmodel',
            options={'verbose_name': 'SizeVariantModel', 'verbose_name_plural': 'SizeVariantModel'},
        ),
        migrations.AlterModelOptions(
            name='usercartmodal',
            options={'verbose_name': 'UserCartModal', 'verbose_name_plural': 'UserCartModal'},
        ),
        migrations.AlterModelOptions(
            name='usersavedmodal',
            options={'verbose_name': 'UserSavedModal', 'verbose_name_plural': 'UserSavedModal'},
        ),
        migrations.AlterField(
            model_name='colorvariantmodel',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sizevariantmodel',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
