# Generated by Django 4.2.3 on 2023-08-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_useraddressmodel_addressesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressesmodel',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
