# Generated by Django 4.2.3 on 2023-08-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_addressesmodel_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressesmodel',
            name='pincode',
            field=models.IntegerField(max_length=6),
        ),
    ]
