# Generated by Django 4.2.3 on 2023-08-11 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_rename_useraddressmodel_useraddressesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressesmodel',
            name='country',
            field=models.CharField(blank=True, default='India', help_text='Enter Your country', max_length=20),
        ),
        migrations.AlterField(
            model_name='addressesmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='api.useraddressesmodel'),
        ),
    ]
