# Generated by Django 4.2.3 on 2023-08-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_addressesmodel_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemsmodal',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
