# Generated by Django 4.2.3 on 2023-08-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_cartitemsmodal_item_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemsmodal',
            name='item_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
