# Generated by Django 4.2.3 on 2023-09-09 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_colorvariantmodel_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colorvariantmodel',
            old_name='color',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sizevariantmodel',
            old_name='size',
            new_name='name',
        ),
    ]
