# Generated by Django 4.2.3 on 2023-09-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_rename_color_colorvariantmodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorvariantmodel',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sizevariantmodel',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
