# Generated by Django 4.2.3 on 2023-09-15 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_delete_userpaymentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='image',
            field=models.ImageField(default='sf', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraddressesmodel',
            name='delievery_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_address', to='api.addressesmodel'),
        ),
    ]
