# Generated by Django 4.2.3 on 2023-09-23 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_remove_cartitemsmodal_item_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryClassModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basemodel')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'CategoryClassModel',
                'verbose_name_plural': 'CategoryClassModel',
                'ordering': ['-updated'],
            },
            bases=('api.basemodel',),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='category_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_class', to='api.categoryclassmodel'),
        ),
    ]
