# Generated by Django 4.2.3 on 2023-09-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_categoryclassmodel_productmodel_category_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryclassmodel',
            options={'verbose_name': 'CategoryClassModel', 'verbose_name_plural': 'CategoryClassModel'},
        ),
        migrations.AddField(
            model_name='categoryclassmodel',
            name='image_alt',
            field=models.CharField(default='image', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersavedmodal',
            name='image_alt',
            field=models.CharField(default='image', max_length=50),
            preserve_default=False,
        ),
    ]
