# Generated by Django 4.2.3 on 2023-09-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_categoryclassmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersavedmodal',
            name='image_alt',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='image_alt',
            field=models.CharField(default='image nhi hii', max_length=50),
            preserve_default=False,
        ),
    ]
