# Generated by Django 4.2.3 on 2023-12-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_remove_usersavedmodal_image_alt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercartmodal',
            name='number_of_items',
        ),
        migrations.RemoveField(
            model_name='usercartmodal',
            name='total_price',
        ),
        migrations.AddField(
            model_name='usercartmodal',
            name='shipping_charge',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
