# Generated by Django 4.2.3 on 2023-12-18 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_remove_usercartmodal_number_of_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercartmodal',
            name='shipping_charge',
        ),
    ]
