# Generated by Django 4.2.7 on 2023-11-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_verify_otp',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Email Verify OTP'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_password_otp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Reset Password OTP'),
        ),
    ]
