# Generated by Django 4.2.7 on 2023-11-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_email_verify_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_verify_otp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='reset_password_otp',
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='OTP'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Otp Type'),
        ),
    ]
