# Generated by Django 4.2.3 on 2023-11-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_customuser_email_verify_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp_type',
            field=models.CharField(blank=True, choices=[('EMAIL_VERIFY', 'EMAIL_VERIFY'), ('LOGIN_VERIFY_EMAIL', 'LOGIN_VERIFY_EMAIL'), ('RESET_USER_PASSWORD', 'RESET_USER_PASSWORD')], max_length=20, null=True, verbose_name='Otp Type'),
        ),
    ]
